### ISSUE TITLE
app crash when clicking "get free API key link"

### ISSUE THREAD

**Issue by k3b** [TylerWilliamson/QuickWeather#3]
The crash (NPE) happend on Android-10.0 device with f-version QuickWeather-1.3.1 from f-droid.

--- 

original crash dump

<pre>
2021-07-17 12:58:52.736 31938-31938/? E/InputEventReceiver: Exception dispatching input event.
2021-07-17 12:58:52.737 31938-31938/? E/MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
2021-07-17 12:58:52.754 31938-31938/? E/MessageQueue-JNI: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
        at c.c.b.c.a.c(:2)
        at com.ominous.tylerutils.view.LinkedTextView$a.onClick(Unknown Source:10)
        at android.text.method.LinkMovementMethod.onTouchEvent(LinkMovementMethod.java:232)
        at android.widget.TextView.onTouchEvent(TextView.java:11166)
        at android.view.View.dispatchTouchEvent(View.java:14002)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3142)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2834)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3142)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2834)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3142)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2834)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3142)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2834)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3142)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2834)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3142)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2834)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3142)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2834)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3142)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2834)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3142)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2834)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3142)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2834)
        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:495)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1868)
        at android.app.Activity.dispatchTouchEvent(Activity.java:4022)
        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:453)
        at android.view.View.dispatchPointerEvent(View.java:14261)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5919)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5722)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5169)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5222)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5188)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5196)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5169)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5222)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5188)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5344)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5196)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5401)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5169)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5222)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5188)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5196)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5169)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8018)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7985)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7946)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8172)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:189)
        at android.os.MessageQueue.nativePollOnce(Native Method)
    	at android.os.M
2021-07-17 12:58:52.755 31938-31938/? D/AndroidRuntime: Shutting down VM
</pre>
    
----

since the binary was obfuscated i downloaded the sources from github and compiled it and reproduced the error:

Stracktrace

------
<pre>
2021-07-17 13:05:32.164 1042-1042/com.ominous.quickweather.debug E/InputEventReceiver: Exception dispatching input event.
2021-07-17 13:05:32.164 1042-1042/com.ominous.quickweather.debug D/AndroidRuntime: Shutting down VM
2021-07-17 13:05:32.172 1042-1042/com.ominous.quickweather.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ominous.quickweather.debug, PID: 1042
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
        at com.ominous.tylerutils.browser.CustomTabs.launchNativeLegacy(CustomTabs.java:212)
        at com.ominous.tylerutils.browser.CustomTabs.launch(CustomTabs.java:175)
        at com.ominous.tylerutils.view.LinkedTextView$CustomTabsURLSpan.onClick(LinkedTextView.java:89)
        at android.text.method.LinkMovementMethod.onTouchEvent(LinkMovementMethod.java:232)
        at android.widget.TextView.onTouchEvent(TextView.java:11166)
        at android.view.View.dispatchTouchEvent(View.java:14002)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3142)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2834)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3142)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2834)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3142)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2834)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3142)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2834)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3142)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2834)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3142)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2834)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3142)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2834)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3142)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2834)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3142)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2834)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3142)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2834)
        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:495)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1868)
        at android.app.Activity.dispatchTouchEvent(Activity.java:4022)
        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:453)
        at android.view.View.dispatchPointerEvent(View.java:14261)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5919)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5722)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5169)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5222)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5188)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5196)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5169)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5222)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5188)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5344)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5196)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5401)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5169)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5222)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5188)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5196)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5169)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8018)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7985)
2021-07-17 13:05:32.174 1042-1042/com.ominous.quickweather.debug E/AndroidRuntime:     at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7946)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8172)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:189)
        at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
        at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:179)
        at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:8102)
        at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:8196)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1043)
        at android.view.Choreographer.doCallbacks(Choreographer.java:866)
        at android.view.Choreographer.doFrame(Choreographer.java:794)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1028)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7615)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
</pre>

---

Note if you want progurad to compress your app but keep original class/method names you can add these to you progurad-rules.pro

<pre>
###############
# I use proguard only to remove unused stuff and to keep the app small.
# I donot want to obfuscate (rename packages, classes, methods, ...) since this is open source
-dontobfuscate
-dontoptimize
-keepnames class ** { *; }
-keepnames interface ** { *; }
-keepnames enum ** { *; }
</pre>

this will avoid dump info like "c.c.b.c.a.c(:2)"

**Comment by TylerWilliamson** [comment]
This crash seems to be due to the CustomTabs browser logic which checks to see if you have a compatible browser. I believe I have resolved this with [this commit in the TylerUtils library](https://github.com/TylerWilliamson/TylerUtils/commit/3a7fbfcbf446c0c448bdc8f28bde71a5e6c30e72).

I will be unable to test this bugfix myself since it is dependent on the all the browser apps on your particular device. I have created the branch [hotfix-customtabs-npe-20210717](https://github.com/TylerWilliamson/QuickWeather/tree/hotfix-customtabs-npe-20210717) to resolve this issue. Please compile this branch to test the fix, or test [this zipped APK](https://github.com/TylerWilliamson/QuickWeather/files/6835002/QuickWeather-1.3.2-DEBUG.apk.zip).

If there is no response after 7 days, I will merge this branch and release this fix.

**Comment by k3b** [comment]
@ TylerWilliamson  i have just tested the zipped apk and it works as expected on my device. thanks for fast fixing

**Comment by TylerWilliamson** [comment]
Fixed in [1.3.2](https://github.com/TylerWilliamson/QuickWeather/releases/tag/1.3.2)
