### ISSUE TITLE
Crash on startup with 2.3.0

### ISSUE THREAD

**Issue by aereaux** [TylerWilliamson/QuickWeather#59]
Hello,

Since updating to 2.3.0 yesterday, I'm getting a crash a few seconds after I open the app:
```
type: crash
osVersion: google/bluejay/bluejay:13/TP1A.221105.002/2022111000:user/release-keys
package: com.ominous.quickweather:54
process: com.ominous.quickweather

java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
	at p4.e.c(SourceFile:109)
	at androidx.lifecycle.LiveData.b(Unknown Source:29)
	at androidx.lifecycle.LiveData.c(SourceFile:56)
	at androidx.lifecycle.LiveData.j(Unknown Source:14)
	at androidx.lifecycle.p.j(Unknown Source:0)
	at androidx.lifecycle.LiveData$a.run(Unknown Source:18)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7904)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)

```

I'm on grapheneos if that makes a difference.

Please let me know what other debugging information might be helpful.

Thanks.

**Comment by TylerWilliamson** [comment]
This is a duplicate of #58 - I have already patched this issue, but F-droid had built with the previous version. Will be resolved after F-droid rebuilds. As a workaround, clear the app data.

I am going to leave this issue open so that other users impacted can see it and the workaround

**Comment by TylerWilliamson** [comment]
Understandable! I "silently" patched the bug because I thought I would be fixing it before F-droid was building. Unfortunately, F-droid must have been in the middle of building. You can tell because F-droid is on version code 54, but GitHub is at version code 55. In hindsight, I should have made this bugfix version 2.3.1.

Also #58 was closed by the person reporting the bug, so by default it doesn't show up in the list of issues here

**Comment by aereaux** [comment]
Just got the new version on f-droid, should be all fixed now.  Thanks again!
